apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name : MYSQL_ROOT_PASSWORD
          value : "guha"
        - name: MYSQL_USER
          value: "guhanandan"
        - name: MYSQL_PASSWORD
          value: "guha"
        - name : MYSQL_DATABASE
          value : "orderdb"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
