apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: guhanandan/ecommerce-order-service:v1.0.2
        env:
        - name : PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-svc:3306/orderdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "guhanandan"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "guha"
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: "com.mysql.cj.jdbc.Driver"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 9090
  type: NodePort
